### ISSUE TITLE
是否用现有bootstrap框架？

### ISSUE THREAD

**Issue by chunyuezhang** [happypeter/resume#2]
1. 昨天晚上我试着用react-bootstrap做导航，但是需要修改太多的css样式
2. 今天试着自己写，但是像链接，窗口缩小后导航收起的功能又显得复杂
3. 下午又试着在昨天react-bootstrap那个基础上改，有些效果还是框架里原有的，我还找不到

所以我想问，接到这种需求的话，到底选择什么方式才是最省时高效的？

**Comment by happypeter** [comment]
像这种高定制性的界面，用 bootstrap 不好弄。

**Comment by happypeter** [comment]
还是手写，其实就是直接照抄原有的 css 即可。

**Comment by happypeter** [comment]
有些 js 插件使用要想想办法。

**Comment by chunyuezhang** [comment]
就是用react也可以使用插件吗

**Comment by happypeter** [comment]
嗯，可以

**Comment by happypeter** [comment]
暂时先写静态的，插件咱们先放一放
